language: python
python:
- '2.7'
- '3.2'
- '3.3'
matrix:
  allow_failures:
    - python: '3.2'
    - python: '3.3'
cache:
  directories:
  - "$HOME/.pip-cache/"
install:
- pip install --download-cache $HOME/.pip-cache -r requirements-dev.txt
script:
- py.test tests/ --cov betty --cov-report term-missing
after_success:
- coveralls
notifications:
  email:
  - csinchok@theonion.com
  on_failure: change
  on_success: change
deploy:
  provider: pypi
  user: csinchok
  password:
    secure: XZlMTIFA8E4jDIbA8m81pH1owQlGLULJ2DXFRsFrKnvmZ/SJOv4F329y2aHW65qvaz67gcNbZg259biL6eZrKG8vIOMzdrC/D3fCgRZSR59tI7WxRj0vX40Pz3E2FzN6QDI8Jbv6+M7wqgHuBDgXWDyEiGRg4arVp1La/dQEg4Y=
  on:
    tags: true
    repo: theonion/betty-cropper
    python: 2.7